#!/usr/bin/env python


class Node:
    def __init__(self, data):
        self.data = data
        self.next = None


def populate(node):
    l = node
    for i in range(10):
        n = Node(i)
        while l.next is not None:
            l = l.next
        l.next = n
        l = node
    return l


def print_list(l):
    while l is not None:
        print(l.data)
        l = l.next


def remove_node(l, data):
    temp = l
    prevnode = None

    while temp is not None:
        if temp.data == data:
            prevnode.next = temp.next
            temp = None
            break
        prevnode = temp
        temp = temp.next
    return l


if __name__ == '__main__':
    f = Node(100)
    lst = populate(f)
    print_list(lst)
    remove_node(lst, 8)
    print_list(lst)