apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: weatherinfo
spec:
  replicas: 1
  template:
    metadata:        
      labels:
        app: weather
    spec:
      containers:
      - name: weatherapp
        image: gcr.io/weatherinfo-179823/production:2.0
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /shared
          name: data
      volumes:
        - name: data
          emptyDir: {}
